### ISSUE TITLE
Deleted Messages are returned in cleartext via !altcaps

### ISSUE THREAD

**Issue by t9ZFauRcOkl0UzNaP0sGRgvLbht4R7Qq** [rom4nik/maubot-alternatingcaps#1]

**Comment by rom4nik** [comment]
Yeah, the plugin doesn't pay attention to redactions currently. I'll make it ignore `!altcaps` when last message gets redacted. 

I suppose it would be better for the bot to navigate backwards in room history until there's a message to process, maybe I'll try to do that too.

**Comment by rom4nik** [comment]
https://github.com/rom4nik/maubot-alternatingcaps/releases/tag/v0.1.2 has this issue fixed.
